#' Plot MAVEn run data.
#'
#' \code{plot_maven_overview} generates four plots to track the instrumental
#' timecourse and requires the full MAVEn dataset (readings + baseline)
#' generated by setting `baseline` = T in \code{read_maven}. The graphic can be
#' automatically saved.
#'
#' @param maven_raw Complete MAVEn dataset including baseline readings.
#' @param outdir Folder where figure should be stored.
#' @param out_filename Figure name.
#' @param out_filetype Figure file type.
#'
#' @return
#' @export
#'
#' @examples
#' plot_maven_overview(maven_raw, outdir = "output", 
#' out_filename = "ExpOverview", out_filetype = ".png"))
plot_maven_overview <- function(maven_raw, maven_experiment = "",
    outdir = "output", out_filename = "ExpOverview", out_filetype = ".png") {
    
    experiment <- maven_raw %>% 
        select(Seconds, TC1, FRC_mlmin, CO2ppm, Chamber) %>% 
        pivot_longer(names_to = "Measurement", 
        values_to = "value", -Seconds) %>% 
        mutate(minutes = Seconds / 60)
    
    p <- ggplot(data = experiment, aes(x = minutes, y = value)) + 
        geom_line() + 
        facet_wrap(~Measurement, scales = "free_y", ncol = 1) + 
        labs(title = "MAVEn run summary", 
            x = "Time (min)", 
            y = "Result value") + 
        theme_classic()
    
    outpath <- file.path(outdir, 
                         out_filename = paste0(Sys.Date(),"_",maven_experiment, 
                                               "_", out_filename, out_filetype))
    
    ggsave(p, filename = outpath, dpi = 300, scale = 1.5, 
        width = 4, height = 4)
    
    return(p)
}


#' Plot fly metabolism trends.
#'
#'\code{metabolism_trend} graphcially displays the fly metabolism data by chamber. The data are adjusted to a standardized measurement reading for illustration. 
#'
#' @param fly_metabolism Fly metabolism dataframe extracted from the MAVEn without baseline using \code{extract_metabolism}. 
#' @param outdir Folder where figure should be stored.
#' @param out_filename Figure name.
#' @param out_filetype Figure file type.
#'
#' @return
#' @export
#'
#' @examples metablism_trend(fly_metabolism, outdir = "output", 
#' out_filename = "", out_filetype = ".png")
metablism_trend <- function(fly_metabolism, maven_experiment = "",
    outdir = "output", out_filename = "MetabolismTrends", out_filetype = ".png") {
    p <- ggplot(data = fly_metabolism %>% 
            mutate(result = co2_convertion(result)), 
        aes(x = measurement_number, y = result, col = cycle)) + 
        geom_point() + 
        facet_wrap(~ Chamber, scales = "free_y") + 
        labs(title = "Fly Metabolism Trends", 
            x = "Measurement Time", 
            y = expression(CO[2] ~ (mu * L ~ h^-1))) + 
        scale_color_viridis_d(option = "D", begin = 0.2, end = 0.8) +
        theme(legend.position = "bottom")
    
    outpath <- file.path(outdir, 
        out_filename = paste0(Sys.Date(),"_",maven_experiment, "_",
            out_filename, out_filetype))
    
    ggsave(p, filename = outpath, dpi = 300, scale = 1.5, 
        width = 7, height = 4)
    
    return(p)
}

#' Visual diagnostic for metabolism data using MAVEn with baseline
#'
#' @param maven_raw Complete MAVEn dataset including baseline readings.
#' @param metabolism_summary_cycle Dataframe calculated by \code{summarize_metabolism} with the "by_cycle" type indicated. 
#' @param outdir Folder where figure should be stored.
#' @param out_filename Figure name.
#' @param out_filetype Figure file type.
#'
#' @return
#' @export
#'
#' @examples metabolism_diag(maven_raw, metabolism_summary_cycle, outdir = "output", out_filename = "MetabolismDiagnostic", out_filetype = ".png")
metabolism_diag <- function(maven_raw, metabolism_summary_cycle, maven_experiment = "",
    outdir = "output", out_filename = "MetabolismDiagnostic", out_filetype = ".png") {
    
    df <- maven_raw %>% 
        select(Seconds:BP_kPa, c_FRC_mlmin:CO2_mlmin, 
        CO2_mlminFly1:CO2_mlminFly16) %>% 
        pivot_longer(cols = CO2_mlminFly1:CO2_mlminFly16, 
            names_to = "parameter", 
            values_to = "result") %>% 
        mutate(parameter = as.numeric(gsub(x = parameter, "CO2_mlminFly", "")),
            result = co2_convertion(result))
    
    
    p <- ggplot(data = df, aes(x = Seconds, y = result)) + 
        facet_grid(parameter ~ .) + 
        geom_line() + 
        geom_point(data = metabolism_summary_cycle %>% 
                mutate(parameter = Chamber), 
            aes(x = median_time, y = median_co2_ul.h, 
                col = parameter), 
            size = 3) + 
        labs(title = "Metabolism diagnostic", 
            x = "Seconds", 
            y = expression(CO[2] ~ (mu * L ~ h^-1))) +
        theme(legend.position = "none")
    
    outpath <- file.path(outdir, 
        out_filename = paste0(Sys.Date(),"_",maven_experiment, "_",
            out_filename, out_filetype))
    
    ggsave(p, filename = outpath, dpi = 300, scale = 1.5, 
        width = 4, height = 8)
    
    return(p)
    
}

#' Plot fly activity trends.
#'
#'\code{activity_trend} graphcially displays the fly activity data by chamber. The data are adjusted to a standardized measurement reading for illustration. 
#'
#' @param fly_metabolism Fly activity dataframe extracted from the MAVEn without baseline using \code{extract_activity}. 
#' @param outdir Folder where figure should be stored.
#' @param out_filename Figure name.
#' @param out_filetype Figure file type.
#'
#' @return
#' @export
#'
#' @examples activity_trend(fly_activity outdir = "output", 
#' out_filename = "", out_filetype = ".png")
activity_trend <- function(fly_activity, maven_experiment = "",
    outdir = "output", out_filename = "ActivityTrends", out_filetype = ".png") {
    
    p <- ggplot(data = fly_activity, 
        aes(x = measurement_number, y = result, col = cycle)) + 
        geom_point() + 
        facet_wrap(~ Chamber, scales = "free_y") + 
        #geom_vline(aes(xintercept = measurement_number_time), 
         #   col = "red", linetype = "dashed") +
        labs(title = "Fly Activity Trends", 
            x = "Measurement Number", 
            y = expression(CO[2] ~ (mu * L ~ h^-1))) + 
        scale_color_viridis_d(option = "D", begin = 0.2, end = 0.8) +
        theme(legend.position = "bottom")
    
    outpath <- file.path(outdir, 
        out_filename = paste0(Sys.Date(),"_",maven_experiment, "_",
                            out_filename, out_filetype))
    
    ggsave(p, filename = outpath, dpi = 300, scale = 1.5, 
        width = 7, height = 4)
    
    return(p)
}



activity_diag <- function(maven_raw,
                          metabolism_summary_cycle,
                          activity_summary_cycle, interval = 60) {
    df <- maven_raw %>%
        select(Seconds:BP_kPa, c_FRC_mlmin:CO2_mlmin, Act_1:Act_16) %>%
        pivot_longer(cols = Act_1:Act_16,
                     names_to = 'parameter',
                     values_to = 'result') %>%
        mutate(parameter = as.numeric(gsub(x = parameter, 'Act_', '')))
    
     maven_summary <- maven_datatable(metabolism_summary_cycle, 
                        activity_summary_cycle, 
                        out_filename = NULL) %>%
         mutate(parameter = Chamber, interval.start = median_time - interval,
                interval.end = median_time + interval)
     maven_summary <- as.data.frame(maven_summary)
    
    p <- ggplot(data = df, aes(x = Seconds, y = result)) +
        geom_tile(data = maven_summary, 
                  aes(x = median_time,y = 15, width = 120, height =30, 
                      fill = parameter)) +
        facet_grid(parameter ~ .) + 
        geom_line() +
        geom_point(data = maven_summary,
                       aes(x = median_time, y = mean_activity, 
                           col = parameter),
                       size = 2) +
        #geom_vline(data = maven_summary,
                  #aes(xintercept = interval.start, col = parameter))+ 
        #geom_vline(data = maven_summary,
                  # aes(xintercept = interval.end, col = parameter))+
        labs(title = 'Activity diagnostic',
             x = 'Seconds',
             y = "")
    
    return(p)
}
